name: "Build AWS Lambda Extension"
description: "Creates a packaged Lambda layer including the Sentry Lambda extension."
inputs:
  artifact_name:
    description: Name of the prepared articact to package into an Lambda extension
    required: true
  zip_file_name:
    description: Name of the zip file that will be created
    required: true
  preserve_symlinks:
    description: Should symbolic links be preserved in the .zip file
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
    - name: Download and configure extension
      shell: bash
      run: |
        echo "Downloading extension..."
        mkdir -p dist-serverless/extensions
        curl -0 --silent --output dist-serverless/extensions/sentry-lambda-extension `curl -s https://release-registry.services.sentry.io/apps/sentry-lambda-extension/latest | jq -r .files.\"sentry-lambda-extension\".url`
        chmod +x dist-serverless/extensions/sentry-lambda-extension
    - name: Check for symlink
      run: |
        echo "--------------------"
        ls -laR dist-serverless/
        echo " XXX dist-serverless/nodejs/node_modules/@sentry/serverless/dist should be a symlink"
        echo "--------------------"
    - name: Zip directory
      shell: bash
      # TODO: does the `-y` in the zip command need single quotes around it?
      run: |
        echo "Creating ${{ inputs.zip_file_name }}..."
        cd dist-serverless
        zip -r ${{ inputs.preserve_symlinks && '-y' }} ../${{ inputs.zip_file_name }} . --exclude \*__pycache__\* --exclude \*.yml
        cd ..
        echo "Done creating ${{ inputs.zip_file_name }}."

        echo "Contents of the created ZIP file:"
        unzip -Z ${{ inputs.zip_file_name }}
    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.zip_file_name }}
