name: "Build AWS Lambda Extension"
description: "Creates a packaged Lambda layer including the Sentry Lambda extension."
inputs:
  artifact_name:
    description: Name of the prepared articact to package into an Lambda extension
    required: true
  zip_file_name:
    description: Name of the zip file that will be created
    required: true
  preserve_symlinks:
    description: Should symbolic links be preserved in the .zip file
    required: false
    default: false
  build_cache_path:
    description: Paths of the build cache
    required: true
  build_cache_key:
    description: Build cache key
    required: true
runs:
  using: "composite"
  steps:
    - name: Check build cache
      uses: actions/cache@v2
      id: cache_built_packages
      with:
        path: ${{ inputs.build_cache_path }}
        key: ${{ inputs.build_cache_key }}
    # - uses: actions/download-artifact@v3
    #   with:
    #     name: ${{ inputs.artifact_name }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Download and configure extension
      shell: bash
      run: |
        echo "Downloading extension..."
        mkdir -p dist-serverless/extensions
        curl -0 --silent --output dist-serverless/extensions/sentry-lambda-extension `curl -s https://release-registry.services.sentry.io/apps/sentry-lambda-extension/latest | jq -r .files.\"sentry-lambda-extension\".url`
        chmod +x dist-serverless/extensions/sentry-lambda-extension
    - name: Check for symlink
      run: |
        echo "--------------------"
        ls -laR packages/serverless/build/aws/dist-serverless/
        echo " XXX packages/serverless/build/aws/dist-serverless/nodejs/node_modules/@sentry/serverless/dist should be a symlink"
        echo "--------------------"
    - name: Zip directory
      shell: bash
      # TODO: does the `-y` in the zip command need single quotes around it?
      run: |
        echo "Creating ${{ inputs.zip_file_name }}..."
        echo "${{ inputs.preserve_symlinks }}"
        echo "${{ inputs.preserve_symlinks && '-y' }}"
        cd dist-serverless
        zip -r ${{ inputs.preserve_symlinks && '-y' }} ../${{ inputs.zip_file_name }} . --exclude \*__pycache__\* --exclude \*.yml
        cd ..
        echo "Done creating ${{ inputs.zip_file_name }}."

        echo "Contents of the created ZIP file:"
        unzip -Z ${{ inputs.zip_file_name }}
    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.zip_file_name }}
