name: "Build AWS Lambda Extension"
description: "Creates a packaged Lambda layer including the Sentry Lambda extension."
inputs:
  artifact_name:
    description: Name of the prepared articact to package into an Lambda extension
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
    - name: Create directory
      shell: bash
      run: |
        ls -alh
        mkdir sentry-lambda-layer/extensions
        echo "pwd $$ ls -alh" > sentry-lambda-layer/extensions/my-extension.sh
        chmod +x sentry-lambda-layer/extensions/my-extension.sh
        curl -0 --silent --output sentry-lambda-layer/relay `curl -s https://release-registry.services.sentry.io/apps/relay/latest | jq -r .files.\"relay-Linux-x86_64\".url`
    - name: Zip directory
      shell: bash
      run: |
        zip -r sentry-lambda-layer.zip sentry-lambda-layer/
        ls -alh
        echo "im zip"
        unzip -Z1 sentry-lambda-layer.zip
